name: pikafish_engine
description: A new Flutter plugin project.
version: 0.0.1
homepage: mdevs.cn

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: cn.chessroad.pikafish_engine
        pluginClass: PikafishEnginePlugin
      ios:
        pluginClass: PikafishEnginePlugin
